### ISSUE TITLE
是否可以支持自动刷新预览窗口

### ISSUE THREAD

**Issue by liuyehcf** [skywind3000/vim-preview#16]
当我选择预览某个条目时，按下p打开预览窗口，切换到下一个条目，需要重新按下p才能刷新预览窗口，是否可以自动刷新

**Comment by fzhzhen1987** [comment]
自动打开预览确实方便很多.找到一个插件有类似功能.但是不会移植.大神受累开发这个功能吧. 
ronakg/quickr-preview.vim 这个插件有自动预览功能.
