### ISSUE TITLE
PreviewSignature not working with guessing the function name

### ISSUE THREAD

**Issue by jhimcras** [skywind3000/vim-preview#5]
Calling PreviewSignature when the cursor on the next of a function name is not working.
For example,
   Func(  <--- cursor is on the left parenthesis and calling PreviewSignature

I found out in the function ' preview#function_define' that checking '<?>' is wrong.
'preview#function_guess' should use when 'name' is '<?>', not ''.

**Comment by skywind3000** [comment]
Then, which line of the source should be modified ??

**Comment by jhimcras** [comment]
auto/preview.vim
line 908 ~ 911
I think it might need to be like this.

	if a:name == ''
		let name = expand('<cword>')
	elseif a:name == '<?>'
		let name = preview#function_guess(line[0:endpos])

**Comment by skywind3000** [comment]
not there, but I fixed. thanks.
