### ISSUE TITLE
Change the highlight in preview window

### ISSUE THREAD

**Issue by tamlok** [skywind3000/vim-preview#7]
Hi,

When we open the preview window to preview a tag, the tag is highlighted using Vim's highlight group, which confuses with searched keyword highlight. Could we use a separate highlight group for the previewed tag? It could link to Vim's search highlight group by default.

Thanks!

**Comment by skywind3000** [comment]
Fine, PR is welcome.

**Comment by tamlok** [comment]
Just did a simple search. It seems that it is already supported?

https://github.com/skywind3000/vim-preview/blob/fb770cc06bacb43b19e84afadcd19103f4ca2cda/autoload/preview.vim#L428

**Comment by skywind3000** [comment]
good
